//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type User struct {
	UUID      string
	Username  string
	Password  []byte
	Salt      []byte
	Role      int32
	BcryptPw  *string
	CreatedAt time.Time
	UpdatedAt time.Time
}
