//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Gallery struct {
	UUID            string `sql:"primary_key"`
	LibraryID       int32
	ArchivePath     string
	Title           string
	TitleNative     *string
	TitleTranslated *string
	Category        *string
	Series          *string
	Released        *string
	Language        *string
	Translated      *bool
	Nsfw            bool
	Hidden          bool
	ImageCount      *int32
	ArchiveSize     *int32
	ArchiveHash     *string
	Thumbnail       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Deleted         bool
	PageThumbnails  *int32
}
