//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Gallery struct {
	UUID        string `sql:"primary_key"`
	LibraryID   int32
	ArchivePath string
	Title       string
	TitleNative *string
	TitleShort  *string
	Released    *string
	Circle      *string
	Artists     *string
	Series      *string
	Category    *string
	Language    *string
	Translated  *bool
	ImageCount  *int32
	ArchiveSize *int32
	ArchiveHash *string
	Thumbnail   *string
	Nsfw        bool
	Hidden      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
