//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type GalleryPref struct {
	UserUUID      string `sql:"primary_key"`
	GalleryUUID   string `sql:"primary_key"`
	Progress      int32
	FavoriteGroup *string
	UpdatedAt     time.Time
}
