//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type GooseDbVersion struct {
	ID        *int32 `sql:"primary_key"`
	VersionID int32
	IsApplied int32
	Tstamp    *time.Time
}
