//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Gallery = Gallery.FromSchema(schema)
	GalleryPref = GalleryPref.FromSchema(schema)
	GalleryTag = GalleryTag.FromSchema(schema)
	GooseDbVersion = GooseDbVersion.FromSchema(schema)
	Library = Library.FromSchema(schema)
	Reference = Reference.FromSchema(schema)
	Session = Session.FromSchema(schema)
	Tag = Tag.FromSchema(schema)
	User = User.FromSchema(schema)
}
