version: '3.8'

services:
  backend:
    hostname: mtsuserver
    image: luukuton/mangatsu-server:latest
    user: 1000:1000
    ports:
      - '5050:5050' # container:host
    restart: always
    environment:
      MTSU_ENV: production
      MTSU_LOG_LEVEL: info
      MTSU_INITIAL_ADMIN_NAME: admin
      MTSU_INITIAL_ADMIN_PW: admin321
      MTSU_BASE_PATHS: freeform1;/archive
      MTSU_CACHE_SIZE: 10000
      MTSU_CACHE_TTL: 604800
      MTSU_DISABLE_CACHE_SERVER: 'false'
      MTSU_VISIBILITY: private
      MTSU_RESTRICTED_PASSPHRASE: secretpassword
      MTSU_REGISTRATIONS: 'false'
      MTSU_JWT_SECRET: 9Wag7sMvKl3aF6K5lwIg6TI42ia2f6BstZAVrdJIq8Mp38lnl7UzQMC1qjKyZCBzHFGbbqsA0gKcHqDuyXQAhWoJ0lcx4K5q
      MTSU_DOMAIN: example.org
      MTSU_HOSTNAME: mtsuserver
      MTSU_PORT: 5050
      MTSU_DATA_PATH: /data
    volumes:
      - "/path/to/data:/data"
      - "rclonevol:/archive:ro"

  frontend:
    hostname: mtsuweb
    image: luukuton/mangatsu-web:latest
    ports:
      - '3030:3030' # container:host
    restart: always
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_MANGATSU_API_URL: https://mangatsu-api.example.com
      NEXT_MANGATSU_IMAGE_HOSTNAME: mangatsu-api.example.com
      PORT: 3030

volumes:
  rclonevol:
    driver: rclone
    driver_opts:
      remote: "manga:/home/user/archive"
      allow_other: "true"
      vfs_cache_mode: full
      vfs_cache_max_age: "720h"
      vfs-cache-max-size: "50G"
      read_only: "true"