package constants

// Languages is a map of languages that are supported by the application.
// TODO: Add more, and convert to international language codes.
var Languages = map[string]bool{
	"afrikaans":  true,
	"albanian":   true,
	"arabic":     true,
	"aramaic":    true,
	"armenian":   true,
	"bengali":    true,
	"bosnian":    true,
	"bulgarian":  true,
	"burmese":    true,
	"catalan":    true,
	"cebuano":    true,
	"chinese":    true,
	"cree":       true,
	"creole":     true,
	"croatian":   true,
	"czech":      true,
	"danish":     true,
	"dutch":      true,
	"english":    true,
	"esperanto":  true,
	"estonian":   true,
	"finnish":    true,
	"french":     true,
	"georgian":   true,
	"german":     true,
	"greek":      true,
	"gujarati":   true,
	"hebrew":     true,
	"hindi":      true,
	"hmong":      true,
	"hungarian":  true,
	"icelandic":  true,
	"indonesian": true,
	"irish":      true,
	"italian":    true,
	"japanese":   true,
	"javanese":   true,
	"kannada":    true,
	"kazakh":     true,
	"khmer":      true,
	"korean":     true,
	"kurdish":    true,
	"ladino":     true,
	"lao":        true,
	"latin":      true,
	"latvian":    true,
	"marathi":    true,
	"mongolian":  true,
	"ndebele":    true,
	"nepali":     true,
	"norwegian":  true,
	"oromo":      true,
	"papiamento": true,
	"pashto":     true,
	"persian":    true,
	"polish":     true,
	"portuguese": true,
	"punjabi":    true,
	"romanian":   true,
	"russian":    true,
	"sango":      true,
	"sanskrit":   true,
	"serbian":    true,
	"shona":      true,
	"slovak":     true,
	"slovenian":  true,
	"somali":     true,
	"spanish":    true,
	"swahili":    true,
	"swedish":    true,
	"tagalog":    true,
	"tamil":      true,
	"telugu":     true,
	"thai":       true,
	"tibetan":    true,
	"tigrinya":   true,
	"turkish":    true,
	"ukrainian":  true,
	"urdu":       true,
	"vietnamese": true,
	"welsh":      true,
	"yiddish":    true,
	"zulu":       true,
}

// LTRLanguages is a list of languages that are written from left to right. TODO: Add more.
var LTRLanguages = []string{
	"arabic",
	"hebrew",
	"japanese",
	"persian",
	"urdu",
}
