name: Container Image

on:
 push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout repo'
      uses: actions/checkout@v3
      
    - name: 'Docker meta'
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          luukuton/mangatsu-server
          ghcr.io/Mangatsu/server
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: 'Login to Docker Hub'
      id: login_dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: 'Login to GitHub Container Registry'
      id: login_ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        
    - name: 'Build and push container'
      id: build_push_container
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}

    - name: Image digests
      run: |
        echo ${{ steps.build_push_container.outputs.digest }}
